language: go

go:
  - "1.11"
  - master

before_install:
  - go get -t -v ./...
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/lint/golint
  - go get github.com/golang/dep/...

install:
  - $GOPATH/bin/dep ensure -v
script:
  - go test -v -race ./...
  - go vet ./...
  - goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")
  - golint $(go list ./... | grep -v /vendor/)
